services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network
    ports:
      - "5432:5432"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservice-network
    ports:
      - "3306:3306"

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local

networks:
  microservice-network:
    driver: bridge
